apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod
  name: nginx-pod
  namespace: ckad
spec:
  containers:
  - image: nginx
    name: nginx-pod
    resources: {}
    volumeMounts:
      - mountPath: /var/log/nginx
        name: logs-storage
  volumes:
    - name: logs-storage
      persistentVolumeClaim:
        claimName: logs-pvc

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
