apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shared-volumes
  name: shared-volumes
  namespace: ckad
spec:
  containers:
    - name: alpine-container-1
      image: alpine:3.12.0
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /etc/a
          name: shared-volume
        # readOnly: true   to limit the access to the volume from this container
    - name: alpine-container-2
      image: alpine:3.12.0
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /etc/b
          name: shared-volume
  volumes:
    - name: shared-volume
      emptyDir: {}
  restartPolicy: Never
status: {}