apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-ping
  namespace: ckad
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid # disallow concurrent jobs
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: google-ping
              image: curlimages/curl:latest
              command: ["sh", "-c", "curl -s google.com"]
