apiVersion: v1
kind: Namespace
metadata:
  name: ckad
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ckad
spec:
  containers:
    - name: nginx
      image: nginx:1.17.10
      ports:
        - containerPort: 80
      env:
        - name: DB_URL
          value: "postgresql://mydb:5432"
        - name: DB_USERNAME
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ckad
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

