apiVersion: v1
kind: Pod
metadata:
  name: loop
  namespace: ckad
spec:
  containers:
    - name: busybox
      image: busybox:1.36.1
      command: ["sh", "-c", "while true; do echo \"Current date: $(date)\"; sleep 1; done"]
  restartPolicy: Never